# Generated by Django 5.2.5 on 2025-08-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidato'), ('company_rep', 'Representante de Empresa')], default='candidate', max_length=15),
        ),
    ]
