# Generated by Django 5.2.5 on 2025-08-25 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_participated_in_selection', models.BooleanField(blank=True, null=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('last_onboarding_date', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_status', to='core.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Estados de Onboarding',
            },
        ),
    ]
