# Generated by Django 5.2.5 on 2025-08-25 22:09

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_onboardingstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-submission_date'], 'verbose_name': 'Reseña', 'verbose_name_plural': 'Reseñas'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Perfil de Usuario', 'verbose_name_plural': 'Perfiles de Usuario'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='short_description',
        ),
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(default='', verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio Web'),
        ),
        migrations.AddField(
            model_name='review',
            name='approval_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Aprobación'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_flagged',
            field=models.BooleanField(default=False, verbose_name='Marcada para Revisión'),
        ),
        migrations.AddField(
            model_name='review',
            name='moderator_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas del Moderador'),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente de Aprobación'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Biografía'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre de la Empresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(max_length=100, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='onboardingstatus',
            name='last_onboarding_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='review',
            name='communication_rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación de Comunicación'),
        ),
        migrations.AlterField(
            model_name='review',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='review',
            name='cons',
            field=models.TextField(verbose_name='Aspectos a Mejorar'),
        ),
        migrations.AlterField(
            model_name='review',
            name='difficulty_rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación de Dificultad'),
        ),
        migrations.AlterField(
            model_name='review',
            name='interview_questions',
            field=models.TextField(blank=True, null=True, verbose_name='Preguntas de la Entrevista'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Aprobada'),
        ),
        migrations.AlterField(
            model_name='review',
            name='job_title',
            field=models.CharField(max_length=200, verbose_name='Cargo o Puesto'),
        ),
        migrations.AlterField(
            model_name='review',
            name='modality',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('híbrido', 'Híbrido')], max_length=20, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='review',
            name='overall_rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación General'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pros',
            field=models.TextField(verbose_name='Aspectos Positivos'),
        ),
        migrations.AlterField(
            model_name='review',
            name='response_time_rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación de Tiempo de Respuesta'),
        ),
        migrations.AlterField(
            model_name='review',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Envío'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.userprofile', verbose_name='Perfil de Usuario'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representatives', to='core.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidato'), ('company_rep', 'Representante de Empresa')], default='candidate', max_length=20, verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='PendingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200, verbose_name='Cargo o Puesto')),
                ('participation_date', models.DateField(verbose_name='Fecha de Participación')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Reseña Enviada')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Actualización')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_reviews', to='core.company', verbose_name='Empresa')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_reviews', to='core.userprofile', verbose_name='Perfil de Usuario')),
            ],
            options={
                'verbose_name': 'Reseña Pendiente',
                'verbose_name_plural': 'Reseñas Pendientes',
                'ordering': ['-participation_date'],
                'unique_together': {('user_profile', 'company')},
            },
        ),
    ]
