# Generated by Django 5.2.5 on 2025-08-25 22:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_company_options_alter_review_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200, verbose_name='Cargo o Puesto')),
                ('participation_date', models.DateField(verbose_name='Fecha de Participación')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas del Staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='Asignación Activa')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Asignación')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Actualización')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='core.company', verbose_name='Empresa')),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Staff que Asignó')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='core.userprofile', verbose_name='Usuario Asignado')),
            ],
            options={
                'verbose_name': 'Asignación del Staff',
                'verbose_name_plural': 'Asignaciones del Staff',
                'ordering': ['-created_at'],
                'unique_together': {('user_profile', 'company')},
            },
        ),
    ]
