# Generated by Django 5.2.4 on 2025-08-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_company_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboardingstatus',
            options={},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidato'), ('company_rep', 'Representante de Empresa'), ('staff', 'Staff del Sistema')], default='candidate', max_length=20, verbose_name='Rol'),
        ),
    ]
