# Generated by Django 5.2.4 on 2025-08-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_onboardingstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='communication_rating',
            field=models.CharField(choices=[('excellent', 'Excelente'), ('good', 'Buena'), ('regular', 'Regular'), ('poor', 'Mala')], max_length=20, verbose_name='Calificación de Comunicación'),
        ),
        migrations.AlterField(
            model_name='review',
            name='difficulty_rating',
            field=models.CharField(choices=[('very_easy', 'Muy Fácil'), ('easy', 'Fácil'), ('moderate', 'Moderada'), ('difficult', 'Difícil'), ('very_difficult', 'Muy Difícil')], max_length=20, verbose_name='Calificación de Dificultad'),
        ),
        migrations.AlterField(
            model_name='review',
            name='response_time_rating',
            field=models.CharField(choices=[('immediate', 'Inmediata'), ('same_day', 'Mismo día'), ('next_day', 'Al día siguiente'), ('few_days', 'En pocos días'), ('slow', 'Lenta')], max_length=20, verbose_name='Calificación de Tiempo de Respuesta'),
        ),
    ]
