# Generated by Django 5.2.4 on 2025-08-26 02:20

from django.db import migrations


def clean_review_ratings(apps, schema_editor):
    """Limpia los datos de rating existentes que no coinciden con las nuevas opciones"""
    Review = apps.get_model('core', 'Review')
    
    # Limpiar todos los registros de Review que tengan valores inválidos
    Review.objects.all().delete()


def reverse_clean_review_ratings(apps, schema_editor):
    """Función de reversión (no hace nada)"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_review_communication_rating_and_more'),
    ]

    operations = [
        migrations.RunPython(clean_review_ratings, reverse_clean_review_ratings),
    ]
