# Generated by Django 5.2.4 on 2025-09-11 15:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20250825_2120'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onboardingstatus',
            options={'verbose_name': 'Estado de Onboarding', 'verbose_name_plural': 'Estados de Onboarding'},
        ),
        migrations.AlterModelOptions(
            name='staffassignment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Asignación de Staff', 'verbose_name_plural': 'Asignaciones de Staff'},
        ),
        migrations.AlterUniqueTogether(
            name='pendingreview',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='staffassignment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, help_text='Adjunta una imagen relacionada con tu experiencia (opcional)', null=True, upload_to='review_images/', verbose_name='Imagen adjunta'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Imagen opcional para tu perfil', null=True, upload_to='avatars/', verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, help_text='Nombre mostrado públicamente en tu perfil', max_length=100, verbose_name='Nombre visible'),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción detallada de la empresa y su actividad', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la empresa está activa en el sistema', verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(help_text='Ciudad o ubicación principal de la empresa', max_length=100, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Nombre completo de la empresa', max_length=200, verbose_name='Nombre de la empresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(help_text='Sector o industria de la empresa (ej: Tecnología, Salud, etc.)', max_length=100, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, help_text='URL del sitio web oficial de la empresa', null=True, verbose_name='Sitio web'),
        ),
        migrations.AlterField(
            model_name='onboardingstatus',
            name='has_participated_in_selection',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ha participado en algún proceso de selección', verbose_name='Ha participado en selección'),
        ),
        migrations.AlterField(
            model_name='onboardingstatus',
            name='last_onboarding_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última fecha de onboarding'),
        ),
        migrations.AlterField(
            model_name='onboardingstatus',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ha completado el proceso de onboarding', verbose_name='Onboarding completado'),
        ),
        migrations.AlterField(
            model_name='onboardingstatus',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_status', to='core.userprofile', verbose_name='Perfil de usuario'),
        ),
        migrations.AlterField(
            model_name='pendingreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='pendingreview',
            name='is_reviewed',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ya completó la reseña', verbose_name='Reseña completada'),
        ),
        migrations.AlterField(
            model_name='pendingreview',
            name='job_title',
            field=models.CharField(help_text='Título del trabajo o puesto al que se postuló', max_length=200, verbose_name='Cargo o puesto'),
        ),
        migrations.AlterField(
            model_name='pendingreview',
            name='participation_date',
            field=models.DateField(help_text='Fecha en que el usuario participó en el proceso de selección', verbose_name='Fecha de participación'),
        ),
        migrations.AlterField(
            model_name='pendingreview',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_reviews', to='core.userprofile', verbose_name='Perfil de usuario'),
        ),
        migrations.AlterField(
            model_name='review',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación'),
        ),
        migrations.AlterField(
            model_name='review',
            name='communication_rating',
            field=models.CharField(choices=[('excellent', 'Excelente'), ('good', 'Buena'), ('regular', 'Regular'), ('poor', 'Mala')], help_text='Evaluación de la comunicación durante el proceso', max_length=20, verbose_name='Calificación de comunicación'),
        ),
        migrations.AlterField(
            model_name='review',
            name='cons',
            field=models.TextField(help_text='Lo que podría mejorar en el proceso', verbose_name='Aspectos a mejorar'),
        ),
        migrations.AlterField(
            model_name='review',
            name='difficulty_rating',
            field=models.CharField(choices=[('very_easy', 'Muy Fácil'), ('easy', 'Fácil'), ('moderate', 'Moderada'), ('difficult', 'Difícil'), ('very_difficult', 'Muy Difícil')], help_text='Nivel de dificultad del proceso de selección', max_length=20, verbose_name='Calificación de dificultad'),
        ),
        migrations.AlterField(
            model_name='review',
            name='interview_questions',
            field=models.TextField(blank=True, help_text='Preguntas que te hicieron durante la entrevista', null=True, verbose_name='Preguntas de entrevista'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Indica si la reseña ha sido aprobada por el staff', verbose_name='Aprobada'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='Indica si la reseña ha sido marcada para revisión', verbose_name='Marcada'),
        ),
        migrations.AlterField(
            model_name='review',
            name='job_title',
            field=models.CharField(help_text='Título del trabajo o puesto al que se postuló', max_length=200, verbose_name='Cargo o puesto'),
        ),
        migrations.AlterField(
            model_name='review',
            name='modality',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('híbrido', 'Híbrido')], help_text='Tipo de trabajo ofrecido', max_length=20, verbose_name='Modalidad de trabajo'),
        ),
        migrations.AlterField(
            model_name='review',
            name='moderator_notes',
            field=models.TextField(blank=True, help_text='Comentarios del staff sobre la reseña', null=True, verbose_name='Notas del moderador'),
        ),
        migrations.AlterField(
            model_name='review',
            name='overall_rating',
            field=models.IntegerField(help_text='Calificación general del 1 al 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación general'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pros',
            field=models.TextField(help_text='Lo que te gustó del proceso de selección', verbose_name='Aspectos positivos'),
        ),
        migrations.AlterField(
            model_name='review',
            name='response_time_rating',
            field=models.CharField(choices=[('immediate', 'Inmediata'), ('same_day', 'Mismo día'), ('next_day', 'Al día siguiente'), ('few_days', 'En pocos días'), ('slow', 'Lenta')], help_text='Velocidad de respuesta de la empresa', max_length=20, verbose_name='Calificación de tiempo de respuesta'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', help_text='Estado de aprobación de la reseña', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='review',
            name='submission_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.userprofile', verbose_name='Perfil de usuario'),
        ),
        migrations.AlterField(
            model_name='staffassignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='staffassignment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si la asignación está activa', verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='staffassignment',
            name='job_title',
            field=models.CharField(help_text='Título del trabajo o puesto al que se postuló el usuario', max_length=200, verbose_name='Cargo o puesto'),
        ),
        migrations.AlterField(
            model_name='staffassignment',
            name='participation_date',
            field=models.DateField(help_text='Fecha en que el usuario participó en el proceso de selección', verbose_name='Fecha de participación'),
        ),
        migrations.AlterField(
            model_name='staffassignment',
            name='staff_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del staff'),
        ),
        migrations.AlterField(
            model_name='staffassignment',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='core.userprofile', verbose_name='Perfil de usuario'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Información personal del usuario', null=True, verbose_name='Biografía'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece el usuario (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidato'), ('company_rep', 'Representante de Empresa'), ('staff', 'Staff del Sistema')], default='candidate', help_text='Rol del usuario en el sistema', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.RemoveField(
            model_name='pendingreview',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='staffassignment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='staffassignment',
            name='updated_at',
        ),
    ]
