# Generated by Django 5.2.4 on 2025-09-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_onboardingstatus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='Colombia', help_text='País donde está ubicada la empresa', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='company',
            name='region',
            field=models.CharField(blank=True, help_text='Región, estado o departamento donde está ubicada la empresa', max_length=100, null=True, verbose_name='Región/Estado'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(help_text='Ciudad principal de la empresa', max_length=100, verbose_name='Ciudad'),
        ),
    ]
