# Generated by Django 5.2.4 on 2025-09-29 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_company_country_company_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(default='Colombia', help_text='País donde está ubicada la empresa - usado en structured data y SEO internacional', max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción detallada de la empresa y su actividad - usado en meta descriptions', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(help_text='Ciudad principal de la empresa - usado para búsquedas geo y SEO local', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Nombre completo de la empresa - usado en SEO y títulos', max_length=200, verbose_name='Nombre de la empresa'),
        ),
        migrations.AlterField(
            model_name='company',
            name='region',
            field=models.CharField(blank=True, help_text='Región, estado o departamento donde está ubicada la empresa - usado para filtros avanzados', max_length=100, null=True, verbose_name='Región/Estado'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(help_text='Sector o industria de la empresa (ej: Tecnología, Salud, etc.) - usado para filtros', max_length=100, verbose_name='Sector'),
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='Título del trabajo o puesto que desempeñaste', max_length=200, verbose_name='Cargo o puesto')),
                ('start_date', models.DateField(help_text='Fecha en que comenzaste a trabajar en esta empresa', verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, help_text='Fecha en que terminaste de trabajar (deja vacío si aún trabajas aquí)', null=True, verbose_name='Fecha de finalización')),
                ('is_current_job', models.BooleanField(default=False, help_text='Indica si actualmente trabajas en esta empresa', verbose_name='Trabajo actual')),
                ('has_review_pending', models.BooleanField(default=False, help_text='Indica si hay una reseña pendiente para esta experiencia laboral', verbose_name='Reseña pendiente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to='core.company', verbose_name='Empresa')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to='core.userprofile', verbose_name='Perfil de usuario')),
            ],
            options={
                'verbose_name': 'Historial Laboral',
                'verbose_name_plural': 'Historiales Laborales',
                'ordering': ['-start_date'],
                'unique_together': {('user_profile', 'company', 'job_title')},
            },
        ),
    ]
