# Generated by Django 5.2.4 on 2025-09-29 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_company_country_alter_company_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffAssignment',
        ),
    ]
