# Generated by Django 5.2.4 on 2025-10-02 22:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('candidate', 'Candidato'), ('company_rep', 'Representante de Empresa'), ('staff', 'Staff del Sistema')], default='candidate', help_text='Rol del usuario en el sistema', max_length=20, verbose_name='Rol')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('bio', models.TextField(blank=True, help_text='Información personal del usuario', null=True, verbose_name='Biografía')),
                ('display_name', models.CharField(blank=True, help_text='Nombre mostrado públicamente en tu perfil', max_length=100, verbose_name='Nombre visible')),
                ('avatar', models.ImageField(blank=True, help_text='Imagen opcional para tu perfil', null=True, upload_to='avatars/', verbose_name='Foto de perfil')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('company', models.ForeignKey(blank=True, help_text='Empresa a la que pertenece el usuario (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company', verbose_name='Empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.CreateModel(
            name='OnboardingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_participated_in_selection', models.BooleanField(default=False, help_text='Indica si el usuario ha participado en algún proceso de selección', verbose_name='Ha participado en selección')),
                ('onboarding_completed', models.BooleanField(default=False, help_text='Indica si el usuario ha completado el proceso de onboarding', verbose_name='Onboarding completado')),
                ('last_onboarding_date', models.DateTimeField(blank=True, null=True, verbose_name='Última fecha de onboarding')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_status', to='accounts.userprofile', verbose_name='Perfil de usuario')),
            ],
            options={
                'verbose_name': 'Estado de Onboarding',
                'verbose_name_plural': 'Estados de Onboarding',
            },
        ),
    ]
