# Generated by Django 5.2.4 on 2025-11-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='availability_status',
            field=models.CharField(blank=True, choices=[('available', 'Disponible'), ('not_available', 'No disponible'), ('actively_looking', 'Buscando activamente')], help_text='Tu disponibilidad laboral actual', max_length=20, null=True, verbose_name='Disponibilidad'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, help_text='Ciudad donde resides', max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, help_text='País donde resides', max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='languages',
            field=models.CharField(blank=True, help_text='Idiomas que manejas (ej: Español, Inglés, Francés)', max_length=200, null=True, verbose_name='Idiomas'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='URL de tu perfil de LinkedIn', null=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, help_text='URL de tu portfolio o sitio web personal', null=True, verbose_name='Portfolio/Website'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specialization',
            field=models.CharField(blank=True, help_text='Tu área de especialización profesional (ej: Desarrollo Web, Marketing Digital)', max_length=200, null=True, verbose_name='Área de especialización'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Años de experiencia profesional', null=True, verbose_name='Años de experiencia'),
        ),
    ]
