# Generated by Django 5.2.4 on 2025-10-02 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='Título del trabajo o puesto que desempeñaste', max_length=200, verbose_name='Cargo o puesto')),
                ('start_date', models.DateField(help_text='Fecha en que comenzaste a trabajar en esta empresa', verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, help_text='Fecha en que terminaste de trabajar (deja vacío si aún trabajas aquí)', null=True, verbose_name='Fecha de finalización')),
                ('is_current_job', models.BooleanField(default=False, help_text='Indica si actualmente trabajas en esta empresa', verbose_name='Trabajo actual')),
                ('has_review_pending', models.BooleanField(default=False, help_text='Indica si hay una reseña pendiente para esta experiencia laboral', verbose_name='Reseña pendiente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to='companies.company', verbose_name='Empresa')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to='accounts.userprofile', verbose_name='Perfil de usuario')),
            ],
            options={
                'verbose_name': 'Historial Laboral',
                'verbose_name_plural': 'Historiales Laborales',
                'ordering': ['-start_date'],
                'unique_together': {('user_profile', 'company', 'job_title')},
            },
        ),
    ]
