# Generated by Django 5.2.4 on 2025-10-02 22:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='Título del trabajo o puesto al que se postuló', max_length=200, verbose_name='Cargo o puesto')),
                ('participation_date', models.DateField(help_text='Fecha en que el usuario participó en el proceso de selección', verbose_name='Fecha de participación')),
                ('is_reviewed', models.BooleanField(default=False, help_text='Indica si el usuario ya completó la reseña', verbose_name='Reseña completada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_reviews', to='companies.company', verbose_name='Empresa')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_reviews', to='accounts.userprofile', verbose_name='Perfil de usuario')),
            ],
            options={
                'verbose_name': 'Reseña Pendiente',
                'verbose_name_plural': 'Reseñas Pendientes',
                'ordering': ['-participation_date'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='Título del trabajo o puesto al que se postuló', max_length=200, verbose_name='Cargo o puesto')),
                ('modality', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('híbrido', 'Híbrido')], help_text='Tipo de trabajo ofrecido', max_length=20, verbose_name='Modalidad de trabajo')),
                ('communication_rating', models.CharField(choices=[('excellent', 'Excelente'), ('good', 'Buena'), ('regular', 'Regular'), ('poor', 'Mala')], help_text='Evaluación de la comunicación durante el proceso', max_length=20, verbose_name='Calificación de comunicación')),
                ('difficulty_rating', models.CharField(choices=[('very_easy', 'Muy Fácil'), ('easy', 'Fácil'), ('moderate', 'Moderada'), ('difficult', 'Difícil'), ('very_difficult', 'Muy Difícil')], help_text='Nivel de dificultad del proceso de selección', max_length=20, verbose_name='Calificación de dificultad')),
                ('response_time_rating', models.CharField(choices=[('immediate', 'Inmediata'), ('same_day', 'Mismo día'), ('next_day', 'Al día siguiente'), ('few_days', 'En pocos días'), ('slow', 'Lenta')], help_text='Velocidad de respuesta de la empresa', max_length=20, verbose_name='Calificación de tiempo de respuesta')),
                ('overall_rating', models.IntegerField(help_text='Calificación general del 1 al 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación general')),
                ('pros', models.TextField(help_text='Lo que te gustó del proceso de selección', verbose_name='Aspectos positivos')),
                ('cons', models.TextField(help_text='Lo que podría mejorar en el proceso', verbose_name='Aspectos a mejorar')),
                ('interview_questions', models.TextField(blank=True, help_text='Preguntas que te hicieron durante la entrevista', null=True, verbose_name='Preguntas de entrevista')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', help_text='Estado de aprobación de la reseña', max_length=20, verbose_name='Estado')),
                ('is_approved', models.BooleanField(default=False, help_text='Indica si la reseña ha sido aprobada por el staff', verbose_name='Aprobada')),
                ('is_flagged', models.BooleanField(default=False, help_text='Indica si la reseña ha sido marcada para revisión', verbose_name='Marcada')),
                ('moderator_notes', models.TextField(blank=True, help_text='Comentarios del staff sobre la reseña', null=True, verbose_name='Notas del moderador')),
                ('image', models.ImageField(blank=True, help_text='Adjunta una imagen relacionada con tu experiencia (opcional)', null=True, upload_to='review_images/', verbose_name='Imagen adjunta')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='companies.company', verbose_name='Empresa')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.userprofile', verbose_name='Perfil de usuario')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-submission_date'],
            },
        ),
    ]
