# Generated by Django 5.2.4 on 2025-10-04 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('companies', '0002_company_logo'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pendingreview',
            unique_together={('user_profile', 'company', 'job_title')},
        ),
    ]
