# Generated by Django 5.2.4 on 2025-10-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_pendingreview_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Indica si la reseña ha sido verificada por el sistema automático', verbose_name='Verificada'),
        ),
        migrations.AddField(
            model_name='review',
            name='verification_category',
            field=models.CharField(choices=[('appropriate', 'Apropiada'), ('toxic', 'Tóxica'), ('hate_speech', 'Discurso de Odio'), ('off_topic', 'Fuera de Lugar'), ('spam', 'Spam'), ('insufficient_content', 'Contenido Insuficiente'), ('error', 'Error en Verificación')], default='appropriate', help_text='Categoría asignada por el sistema de verificación', max_length=20, verbose_name='Categoría de verificación'),
        ),
        migrations.AddField(
            model_name='review',
            name='verification_confidence',
            field=models.FloatField(default=0.0, help_text='Nivel de confianza del sistema de verificación (0.0 a 1.0)', verbose_name='Confianza de verificación'),
        ),
        migrations.AddField(
            model_name='review',
            name='verification_reason',
            field=models.CharField(blank=True, help_text='Razón por la cual la reseña fue aprobada o rechazada', max_length=200, verbose_name='Razón de verificación'),
        ),
    ]
