# Generated by Django 5.2.4 on 2025-10-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre completo de la empresa - usado en SEO y títulos', max_length=200, verbose_name='Nombre de la empresa')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada de la empresa y su actividad - usado en meta descriptions', verbose_name='Descripción')),
                ('sector', models.CharField(help_text='Sector o industria de la empresa (ej: Tecnología, Salud, etc.) - usado para filtros', max_length=100, verbose_name='Sector')),
                ('location', models.CharField(help_text='Ciudad principal de la empresa - usado para búsquedas geo y SEO local', max_length=100, verbose_name='Ciudad')),
                ('region', models.CharField(blank=True, help_text='Región, estado o departamento donde está ubicada la empresa - usado para filtros avanzados', max_length=100, null=True, verbose_name='Región/Estado')),
                ('country', models.CharField(default='Colombia', help_text='País donde está ubicada la empresa - usado en structured data y SEO internacional', max_length=100, verbose_name='País')),
                ('website', models.URLField(blank=True, help_text='URL del sitio web oficial de la empresa', null=True, verbose_name='Sitio web')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la empresa está activa en el sistema', verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
    ]
