# Generated by Django 5.2.4 on 2025-10-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo de la empresa', null=True, upload_to='company_logos/', verbose_name='Logo'),
        ),
    ]
